
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const ON_SEARCH = 'ON_SEARCH'
const SET_PARKS = 'SET_PARKS'
const FETCH_PARKS = 'FETCH_PARKS'
const ADD_PARK = 'ADD_PARK'
const DELETE_PARK = 'DELETE_PARK'
const SET_CURRENT_PARK = 'SET_CURRENT_PARK'
const SET_USER_PARKS = 'SET_USER_PARKS'
const ADD_PARK_TO_STORE = 'ADD_PARK_TO_STORE'
const REMOVE_PARK_FROM_USER = 'REMOVE_PARK_FROM_USER'
const CLEAR_PARKS_STORE = 'CLEAR_PARKS_STORE'

export {LOGIN ,LOGOUT, ON_SEARCH, SET_PARKS, FETCH_PARKS,
   ADD_PARK, DELETE_PARK, SET_CURRENT_PARK, SET_USER_PARKS,
    ADD_PARK_TO_STORE, REMOVE_PARK_FROM_USER, CLEAR_PARKS_STORE}